# banking-account-service.yml
spring:
  application:
    name: banking-account-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ACCOUNTDB
    username: account_user
    password: account_pass
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
