# client-service.yml
spring:
  application:
    name: client-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/CLIENTDB
    username: client_user
    password: client_pass
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
