# credit-service.yml
spring:
  application:
    name: credit-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/CREDITDB
    username: credit_user
    password: credit_pass
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
